### PR TITLE
Fixes #190 - Workaround for service apply bug

### LINKED ISSUE #190: Director 1.10 - Error when modifying service apply rules
### Description

Apparently, director versions later than 1.8.1 introduced a change in the API endpoint "director/serviceapplyrules".

This change broke functionality in module "icinga_service_apply.py"

Broken function:
- Existing service apply rule objects cannot be modified.

### Reproduction steps

1. Create a service apply rule object using ansible.
2. Run the same playbook again. 
3. Receive an error.
```
TASK [Add service apply rule to icinga] ********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "exception when deleting: 'id'"}
```

### Current Behavior

Error displayed when modifying an object. 

### Expected Behavior

Object is modified, no error required.

### Additional information

The module "icinga_service_apply.py" looks for "id" key in the returned JSON object. The key "id" was removed from the API endpoint JSON output in Director 1.10 or even earlier. 

Director 1.8.1
```
./director-curl GET director/serviceapplyrules
{
    "assign_filter": "host.vars.cisco_check_config_nwc=true",
    "check_interval": "600",
    "id": "16",                                                                       ####### !!! #######
    "imports": [
        "__cisco-check-config__"
    ],
    "object_name": "__nwc__cisco_check_config",
    "object_type": "apply",
    "retry_interval": "300"
},
...
```

Director 1.10.1 / 1.10.2
```
./director-curl GET director/serviceapplyrules
{
    "assign_filter": "host.vars.cisco_check_config_nwc=true",
    "check_interval": "600",
    "fields": [],
    "imports": [
        "__cisco-check-config__"
    ],
    "object_name": "__nwc__cisco_check_config",
    "object_type": "apply",
    "retry_interval": "300"
}
...
```

A fix that seems to do the trick (taken from service_template.py):
```
# diff icinga_service_apply.py_mod icinga_service_apply.py_orig
325c354
<     icinga_object = Icinga2APIObject(module=module, path="/service", data=data)
---
>     icinga_object = ServiceApplyRule(module=module, data=data)
```
This also makes Class ServiceApplyRule obsolete, but service template also does not have one...

### PR DESCRIPTION
**Pull request by gianmarco-mameli**
Fixes #190 

I've found that changing all instances of 'find_by="id"' field with 'find_by="uuid"', in the ServiceApplyClass, actually made the error disappear. Unfortunately at this time I've only a completely empty Icinga installation, so I can't use the service apply created to any host, but 'm able to perform operations on Service Apply
If you run some test with my fix the error is not present and you are now able to Add/Delete service apply in idempotent way

What do you think?

Thanks

### CODE REVIEW

**Comment by rndmh3ro** [comment]
The implementation looks good from first sight and the idea is great!
Now the tests have to pass, too. There seems to be a problem when deleting objects. I don't know yet what is the problem.

**Comment by gianmarco-mameli** [comment]
you're right, something strange beacause the tests at the first run fail at the 'Add service apply rule with command_endpoint', but at the second run with verbosity fail at the previous task 'Add service apply rule to icinga'. I'll try to fix it

**Comment by rndmh3ro** [comment]
I just checked why it's failing and the answer is easy: we're testing against the director version 1.9.0, where uuid's don't exist, yet.
So we probably have to check which director-version is used so we can use either uuid's or the old id-approach. However I didn't find an API-endpoint on the director-side that tells me what version is running.

**Comment by gianmarco-mameli** [comment]
Take a look at my last commit, i understand that is a workaround, and I'm glad if anyone find a better solution, but maybe it's a temp fix to the bug, let's see if the tests fails again

**Comment by gianmarco-mameli** [comment]
Ok, sorry I see some pylint errors, I'm going to check and resolve

**Comment by rndmh3ro** [comment]
This seems to work now, at least for the tested director-version.

What I'd like to do now is update our testing-strategy to test more icinga-director versions, starting from 1.8 to 1.11. But that's nothing for you to do, I'll do this. :)


Anyway, thanks for this PR!

**Comment by gianmarco-mameli** [comment]
Ok, very good, I've pushed the lint fix and cleaned the comments

**Comment by rndmh3ro** [comment]
Tested here: https://github.com/telekom-mms/ansible-collection-icinga-director/pull/242/checks

works for 1.8.1 - that's enough for me.

**Review by rndmh3ro — APPROVED** [review]

**Pull request merged**
